# Reflection on Cloud Computing Concepts

Cloud computing has become an important part of my daily life because I regularly use different applications and online services that depend on cloud technology. Three cloud services that I commonly use are Google Drive, Canva, and GCash. These applications allow me to access services and information through the internet without depending entirely on the storage and computing resources of my personal device.

Google Drive can be classified as Software as a Service (SaaS) because it provides users with ready-to-use cloud-based services for storing, managing, and sharing files. Its deployment model can be considered Public Cloud because the service is provided over the internet and is available to many users through their Google accounts. I use Google Drive to store school documents and access them from different devices.

Canva is also an example of SaaS because it provides an online graphic design platform that users can access through a web browser or application. It can be classified under the Public Cloud deployment model because its services are hosted by the provider and made available to users through the internet. I use Canva to create presentations, posters, and other school-related designs.

GCash is another cloud-based application that I use for digital financial transactions. It can be considered SaaS because users access its services through an application without managing the underlying cloud infrastructure. Its deployment model can be considered Public Cloud because the service is delivered online to a large number of users.

Git and GitHub are also important when working with cloud projects. Version control allows developers and teams to track changes, restore previous versions, and work on projects without accidentally losing important files. GitHub provides a centralized platform where team members can collaborate, review changes, and manage project files. In cloud infrastructure projects, version control can also help teams document configuration changes and reduce errors. Overall, cloud computing and version control work together to make technology projects more organized, accessible, collaborative, and reliable.
